title: HopeLynxBlog
author: HopeLynx
email: hopelynxstudio@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
 Grigorii Sizov | HopeLynx - Python Developer. Bioinformatician. Data scientist
show_excerpts: true # set to true to show excerpts on the homepage
remote_theme: samarsault/texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Grigorii Sizov
  tagline: Developer. Bioinformatician. Data scientist
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
   # twitter: ...
    github:  Hopelynx
    linkedIn: in/grigorii-sizov-2075461a8
    mail: hopelynxstudio@gmail.com
 #   vk: grigsiz
   # telegram: grigsiz
  #  kaggle: ...
  #  wechat: test
    rss: rss

  navigation:
    - title: Home
      url: ""
    - title: About
      url: "/about"
    - title: Resume
      url: "/resume.pdf"
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
#  - jekyll-feed
